In [23]:
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [25]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [26]:
## Define the vocabulary size
vocab_size=10000

In [27]:
### One Hot Representation
one_hot_repr=[one_hot(word,vocab_size) for word in sent]
one_hot_repr

[[4069, 4595, 1107, 7813],
 [4069, 4595, 1107, 751],
 [4069, 5044, 1107, 8133],
 [3089, 6641, 8306, 7633, 8311],
 [3089, 6641, 8306, 7633, 562],
 [2219, 4069, 856, 1107, 1482],
 [118, 4557, 9792, 7633]]

In [28]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [29]:
import numpy as np

In [30]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4069 4595 1107 7813]
 [   0    0    0    0 4069 4595 1107  751]
 [   0    0    0    0 4069 5044 1107 8133]
 [   0    0    0 3089 6641 8306 7633 8311]
 [   0    0    0 3089 6641 8306 7633  562]
 [   0    0    0 2219 4069  856 1107 1482]
 [   0    0    0    0  118 4557 9792 7633]]


In [31]:
## feature representation
dim=10

In [32]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [33]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array([[[-0.02102311, -0.02269964,  0.00473105, -0.01329557,
          0.04259929,  0.04831981,  0.00153568,  0.04225958,
          0.03775031,  0.01191325],
        [-0.02102311, -0.02269964,  0.00473105, -0.01329557,
          0.04259929,  0.04831981,  0.00153568,  0.04225958,
          0.03775031,  0.01191325],
        [-0.02102311, -0.02269964,  0.00473105, -0.01329557,
          0.04259929,  0.04831981,  0.00153568,  0.04225958,
          0.03775031,  0.01191325],
        [-0.02102311, -0.02269964,  0.00473105, -0.01329557,
          0.04259929,  0.04831981,  0.00153568,  0.04225958,
          0.03775031,  0.01191325],
        [ 0.01414705, -0.0221638 ,  0.0022014 , -0.02232035,
          0.00120211, -0.01272051,  0.0319442 ,  0.01450663,
          0.02807928, -0.00465661],
        [-0.03444508, -0.02859842, -0.03344755,  0.00199836,
          0.02076591,  0.03843877,  0.01567503, -0.00029043,
          0.0047755 ,  0.04558549],
        [ 0.03530486, -0.01788666,  0.00245447,  0.0

In [35]:
embedded_docs[0]

array([   0,    0,    0,    0, 4069, 4595, 1107, 7813], dtype=int32)